baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'CarbonTracker'

google_analytics_id: null
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "50px"
footer:
  copyright_text: © 2020 CarbonTracker Pty Ltd.

seo:
  meta_og_title: "CarbonTracker"
  meta_og_type: "website"
  meta_og_url: "https://carbontracker.com.au/"
  meta_og_description: "CarbonTracker"
  meta_twitter_card: "summary"

sass:
  style: compact # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
